package org.osndevs.liteorm.database;

import org.osndevs.liteorm.models.Column;
import org.osndevs.liteorm.models.ColumnDescriptor;
import org.osndevs.liteorm.models.ColumnType;
import org.osndevs.liteorm.models.ModelDescriptor;
import org.osndevs.liteorm.models.PrimaryKey;
import org.osndevs.liteorm.models.Model;
import org.osndevs.liteorm.utils.DatabaseUtils;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Type;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class QueryBuilder {
    Database database;
    Map<Class<?>, ModelDescriptor> fieldCache = new HashMap<>();

    public QueryBuilder(Database database) {
        this.database = database;
    }

    protected <T> ModelDescriptor cacheDescriptor(T model) {
        Class<?> klass = model.getClass();
        List<ColumnDescriptor> columnDescriptorList = new ArrayList<>();
        Field[] fields = klass.getDeclaredFields();
        ColumnDescriptor primaryKeyDescriptor = null;

        for (Field field : fields) {
            Column columnAnnotation = field.getAnnotation(Column.class);

            if (columnAnnotation == null) {
                continue;
            }


            String name = columnAnnotation.actualName();

            if (name.isEmpty()) {
                name = field.getName();
                name = name.substring(0, 1).toLowerCase() +
                        name.substring(1).replaceAll("([A-Z])", "_$1").toLowerCase();
            }

            ColumnType type = columnAnnotation.type();

            if (type == ColumnType.DEFAULT) {
                type = getColumnType(field);
            }

            Map<Class<?>, Annotation> otherAnnotations = new HashMap<>();
            PrimaryKey primaryKeyAnnotation = field.getAnnotation(PrimaryKey.class);

            if (primaryKeyAnnotation != null) {
                otherAnnotations.put(PrimaryKey.class, primaryKeyAnnotation);
            }

            final var descriptor = new ColumnDescriptor(name, type, field, columnAnnotation, otherAnnotations);
            columnDescriptorList.add(descriptor);

            if (primaryKeyAnnotation != null) {
                if (primaryKeyDescriptor != null) {
                    throw new RuntimeException("Multiple primary keys are not allowed");
                }

                primaryKeyDescriptor = descriptor;
            }
        }

        Model modelAnnotation = DatabaseUtils.getModelAnnotation(klass);
        ModelDescriptor descriptor = new ModelDescriptor(DatabaseUtils.getTableNameFromModel(klass), primaryKeyDescriptor, columnDescriptorList, modelAnnotation);
        fieldCache.put(klass, descriptor);
        return descriptor;
    }

    protected <T> ModelDescriptor getDescriptor(T model) {
        Class<?> klass = model.getClass();
        ModelDescriptor descriptor = fieldCache.get(klass);

        if (descriptor == null) {
            descriptor = cacheDescriptor(model);
        }

        return descriptor;
    }

    protected ColumnType getColumnType(Field field) {
        Type type = field.getType();

        if (type == Integer.class || type == int.class) {
            return ColumnType.INTEGER;
        }
        else if (type == Long.class || type == long.class) {
            return ColumnType.LONG;
        }
        else if (type == Boolean.class || type == boolean.class) {
            return ColumnType.BOOLEAN;
        }
        else if (type == String.class) {
            return ColumnType.STRING;
        }

        throw new RuntimeException("Invalid column type");
    }

    @SafeVarargs
    public final <T> PreparedStatement buildInsertStatement(T... models) throws SQLException {
        ModelDescriptor modelDescriptor = getDescriptor(models[0]);
        String query = "insert into " + modelDescriptor.tableName();
        StringBuilder columns = new StringBuilder();
        boolean ignorePrimaryKey = false;

        for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors()) {
            if (columnDescriptor == modelDescriptor.primaryKeyDescriptor()) {
                Annotation primaryKeyAnnotation = columnDescriptor.otherAnnotations().get(PrimaryKey.class);

                if (primaryKeyAnnotation instanceof PrimaryKey && ((PrimaryKey) primaryKeyAnnotation).autoGenerated()) {
                    ignorePrimaryKey = true;
                    continue;
                }
            }

            if (!columns.isEmpty()) {
                columns.append(", ");
            }

            columns.append('"').append(columnDescriptor.name()).append('"');
        }

        query += "(" + columns + ") ";

        StringBuilder values = new StringBuilder();

        for (var _ : models) {
            StringBuilder valueRow = new StringBuilder();

            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors()) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor() && ignorePrimaryKey) {
                    continue;
                }

                if (!valueRow.isEmpty()) {
                    valueRow.append(", ");
                }

                valueRow.append("?");
            }

            if (!values.isEmpty()) {
                values.append(", ");
            }

            values.append("(").append(valueRow).append(")");
        }

        query += "values " + values + ";";

        PreparedStatement statement = database.getConnection().prepareStatement(query);
        int index = 1;

        for (var model : models) {
            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors()) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor() && ignorePrimaryKey) {
                    continue;
                }

                columnDescriptor.field().setAccessible(true);

                try {
                    Object value = columnDescriptor.field().get(model);

                    switch (columnDescriptor.type()) {
                        case STRING, TEXT -> statement.setString(index++, (String) value);
                        case BOOLEAN -> statement.setBoolean(index++, (Boolean) value);
                        case INTEGER -> statement.setInt(index++, (Integer) value);
                        case LONG -> statement.setLong(index++, (Long) value);
                        case DEFAULT -> throw new RuntimeException("DEFAULT column type encountered during insert");
                    }
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        return statement;
    }
}
