package org.osndevs.liteorm.sql;

import org.osndevs.liteorm.database.Database;
import org.osndevs.liteorm.models.ColumnDescriptor;
import org.osndevs.liteorm.models.ModelDescriptor;
import org.osndevs.liteorm.models.PrimaryKey;

import java.lang.annotation.Annotation;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class InsertQuery<T> extends Query {
    List<InsertQueryValue> boundValues;

    public InsertQuery(Database database, Class<T> clazz, T[] models) {
        super(database);
        this.sql = "";
        processModels(clazz, models);
    }

    private void processModels(Class<T> clazz, T[] models) {
        if (models.length == 0) {
            throw new RuntimeException("No model to operate on");
        }

        QueryBuilder queryBuilder = database.getQueryBuilder();

        @SuppressWarnings("unchecked")
        ModelDescriptor<T> modelDescriptor = queryBuilder.getDescriptor((Class<T>) models[0].getClass());
        String query = "insert into " + modelDescriptor.tableName;
        StringBuilder columns = new StringBuilder();
        boolean ignorePrimaryKey = false;

        for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
            if (columnDescriptor == modelDescriptor.primaryKeyDescriptor) {
                Annotation primaryKeyAnnotation = columnDescriptor.otherAnnotations().get(PrimaryKey.class);

                if (primaryKeyAnnotation instanceof PrimaryKey && ((PrimaryKey) primaryKeyAnnotation).autoGenerated()) {
                    ignorePrimaryKey = true;
                    continue;
                }
            }

            if (!columns.isEmpty()) {
                columns.append(", ");
            }

            columns.append('"').append(columnDescriptor.name()).append('"');
        }

        query += "(" + columns + ") ";

        StringBuilder values = new StringBuilder();

        for (var model : models) {
            if (!clazz.isInstance(model)) {
                throw new RuntimeException("Invalid model on a single insert() call: All models must have the same type");
            }

            StringBuilder valueRow = new StringBuilder();

            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor && ignorePrimaryKey) {
                    continue;
                }

                if (!valueRow.isEmpty()) {
                    valueRow.append(", ");
                }

                valueRow.append("?");
            }

            if (!values.isEmpty()) {
                values.append(", ");
            }

            values.append("(").append(valueRow).append(")");
        }

        query += "values " + values;

        boundValues = new ArrayList<>();
        int index = 1;

        for (var model : models) {
            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor && ignorePrimaryKey) {
                    continue;
                }

                columnDescriptor.field().setAccessible(true);

                try {
                    Object value = columnDescriptor.field().get(model);
                    boundValues.add(new InsertQueryValue(index++, columnDescriptor, value));
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        sql = query;
    }

    public InsertQuery<T> onConflictDoNothing() {
        sql += " ON CONFLICT DO NOTHING ";
        return this;
    }

    public InsertQuery<T> append(String sql) {
        this.sql += sql;
        return this;
    }

    @Override
    public PreparedStatement toStatement() throws SQLException {
        // noinspection SqlSourceToSinkFlow
        PreparedStatement statement = database.getConnection().prepareStatement(sql + ";");

        for (InsertQueryValue boundValue : boundValues) {
            switch (boundValue.getType()) {
                case STRING, TEXT -> statement.setString(boundValue.index(), (String) boundValue.value());
                case INTEGER -> statement.setInt(boundValue.index(), (Integer) boundValue.value());
                case LONG -> statement.setLong(boundValue.index(), (Long) boundValue.value());
                case BOOLEAN -> statement.setBoolean(boundValue.index(), (Boolean) boundValue.value());
                case DEFAULT -> throw new RuntimeException("Encountered DEFAULT type when building prepared statement");
            }
        }

        return statement;
    }
}
