package org.osndevs.liteorm.sql;

import org.osndevs.liteorm.database.Database;
import org.osndevs.liteorm.models.ColumnDescriptor;
import org.osndevs.liteorm.models.ModelDescriptor;
import org.osndevs.liteorm.models.PrimaryKey;

import java.lang.annotation.Annotation;
import java.util.ArrayList;

public class InsertQuery<M> extends Query<InsertQuery<M>> {
    public InsertQuery(Database database, Class<M> clazz, M[] models) {
        super(database);
        this.sql = "";
        processModels(clazz, models);
    }

    private void processModels(Class<M> clazz, M[] models) {
        if (models.length == 0) {
            throw new RuntimeException("No model to operate on");
        }

        QueryBuilder queryBuilder = database.getQueryBuilder();

        @SuppressWarnings("unchecked")
        ModelDescriptor<M> modelDescriptor = queryBuilder.getDescriptor((Class<M>) models[0].getClass());
        String query = "insert into " + modelDescriptor.tableName;
        StringBuilder columns = new StringBuilder();
        boolean ignorePrimaryKey = false;

        for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
            if (columnDescriptor == modelDescriptor.primaryKeyDescriptor) {
                Annotation primaryKeyAnnotation = columnDescriptor.otherAnnotations().get(PrimaryKey.class);

                if (primaryKeyAnnotation instanceof PrimaryKey && ((PrimaryKey) primaryKeyAnnotation).autoGenerated()) {
                    ignorePrimaryKey = true;
                    continue;
                }
            }

            if (!columns.isEmpty()) {
                columns.append(", ");
            }

            columns.append('"').append(columnDescriptor.name()).append('"');
        }

        query += "(" + columns + ") ";

        StringBuilder values = new StringBuilder();

        for (var model : models) {
            if (!clazz.isInstance(model)) {
                throw new RuntimeException("Invalid model on a single insert() call: All models must have the same type");
            }

            StringBuilder valueRow = new StringBuilder();

            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor && ignorePrimaryKey) {
                    continue;
                }

                if (!valueRow.isEmpty()) {
                    valueRow.append(", ");
                }

                valueRow.append("?");
            }

            if (!values.isEmpty()) {
                values.append(", ");
            }

            values.append("(").append(valueRow).append(")");
        }

        query += "values " + values;

        boundedValues = new ArrayList<>();
        boundedValueIndex = 1;

        for (var model : models) {
            for (ColumnDescriptor columnDescriptor : modelDescriptor.columnDescriptors) {
                if (columnDescriptor == modelDescriptor.primaryKeyDescriptor && ignorePrimaryKey) {
                    continue;
                }

                columnDescriptor.field().setAccessible(true);

                try {
                    Object value = columnDescriptor.field().get(model);
                    boundedValues.add(new BoundedValue(boundedValueIndex++, columnDescriptor.type(), value));
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        sql = query;
    }

    public InsertQuery<M> onConflictDoNothing() {
        sql += " ON CONFLICT DO NOTHING ";
        return this;
    }
}
